from .home import *
from .master_user import *
from .auth import *
from .wisata import *
from .penginapan import *
from .faq import *
from .kritiksaran import *
from .kontak import *
from .berita import *
from .infografis import *
from .tentang_views import *