# Generated by Django 5.2.1 on 2025-05-23 04:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import wisata_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='images/avatar/avatar-default.svg', null=True, upload_to='images/avatar/')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_prov', 'Admin Kabupaten'), ('admin_kab', 'Admin Kecamatan')], default='user', max_length=50)),
                ('email_verification_token', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', wisata_app.models.Master_UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('berita_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='berita/thumbnails/')),
                ('konten', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tags', models.CharField(help_text='Pisahkan dengan koma (,) jika lebih dari satu tag', max_length=255)),
                ('kategori', models.CharField(choices=[('berita', 'Berita'), ('event', 'Event')], max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('pertanyaan', models.TextField()),
                ('jawaban', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Infografis',
            fields=[
                ('infografis_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='infografis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infografis',
                'verbose_name_plural': 'Infografis',
            },
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
                ('jam_operasional', models.CharField(blank=True, max_length=100, null=True)),
                ('link_maps', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Penginapan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('penginapan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_penginapan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('fasilitas', models.TextField()),
                ('alamat', models.TextField()),
                ('maps', models.URLField()),
                ('harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('embed_maps', models.TextField(blank=True, null=True)),
                ('no_telepon', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TentangKami',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('tentang_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('deskripsi', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated_by', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wisata',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wisata_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_wisata', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('bahari', 'Bahari'), ('sejarah', 'Sejarah'), ('kuliner', 'Kuliner')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('fasilitas', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('alamat', models.TextField()),
                ('maps', models.URLField()),
                ('harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('embed_maps', models.TextField(blank=True, null=True)),
                ('jam_operasional', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kritiksaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('kritik', models.TextField()),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenginapanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='penginapan/images')),
                ('penginapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wisata_app.penginapan')),
            ],
        ),
        migrations.CreateModel(
            name='RatingPenginapan',
            fields=[
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('reply_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penginapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='wisata_app.penginapan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TentangKamiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tentang/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tentang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wisata_app.tentangkami')),
            ],
        ),
        migrations.CreateModel(
            name='RatingWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('reply_date', models.DateTimeField(blank=True, null=True)),
                ('wisata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='wisata_app.wisata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WisataImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wisata/images')),
                ('wisata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wisata_app.wisata')),
            ],
        ),
    ]
