# Generated by Django 3.2 on 2024-12-11 21:41

from django.db import migrations, models
import django.utils.timezone
import uuid
import wisata_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='images/avatar/default_avatar.png', null=True, upload_to='images/avatar/')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_prov', 'Admin Provinsi'), ('admin_kab', 'Admin Kabupaten')], default='user', max_length=50)),
                ('email_verification_token', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', wisata_app.models.Master_UserManager()),
            ],
        ),
    ]
