# Generated by Django 3.2 on 2024-12-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisata_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wilayah', models.CharField(max_length=255)),
                ('kode_wilayah', models.CharField(max_length=50, unique=True)),
                ('parent_wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_wilayah', to='wisata_app.masterwilayah')),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
            },
        ),
    ]
