# Generated by Django 3.2 on 2024-12-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisata_app', '0002_masterwilayah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterWilayah',
        ),
    ]
